main: water.of.cup.cameras.Camera
name: Cameras
version: '1.05'
description: Take Pictures.
author: Nicholas Kopiwoda
api-version: 1.14
commands:
  takepicture:
    description: take a picture